"""update

Revision ID: b721fa604226
Revises: 0dafbb8add08
Create Date: 2024-11-22 17:13:13.422916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b721fa604226'
down_revision: Union[str, None] = '0dafbb8add08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # Создаем таблицу users
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('apikey', sa.String, unique=True, nullable=False),
        sa.Column('name', sa.String(50), nullable=False),
    )

    # Создаем таблицу tweets
    op.create_table(
        'tweets',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('author_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False),
        sa.Column('content', sa.String(280), nullable=False),
    )

    # Создаем таблицу likes
    op.create_table(
        'likes',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=True),
        sa.Column('tweet_id', sa.Integer, sa.ForeignKey('tweets.id'), nullable=True),
    )

    # Создаем таблицу media
    op.create_table(
        'media',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('file_path', sa.String, nullable=False),
        sa.Column('tweet_id', sa.Integer, sa.ForeignKey('tweets.id'), nullable=True),
    )

    # Создаем таблицу follows
    op.create_table(
        'follows',
        sa.Column('follower_id', sa.Integer, sa.ForeignKey('users.id'), primary_key=True),
        sa.Column('following_id', sa.Integer, sa.ForeignKey('users.id'), primary_key=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tweets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='tweets_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tweets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('apikey', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('apikey', name='users_apikey_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tweet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], name='likes_tweet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='likes_pkey')
    )
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tweet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], name='media_tweet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='media_pkey')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follows_follower_id_fkey'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='follows_following_id_fkey'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id', name='follows_pkey')
    )
    # ### end Alembic commands ###
