services:
#  test_database:
#    image: postgres:17.1
#    environment:
#      POSTGRES_PASSWORD: test
#      POSTGRES_USER: test
#      POSTGRES_DB: test_twitter
#    ports:
#      - "5433:5432"

  database:
    image: postgres:17.1
    volumes:
      - ./server/database/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"

#  client:
#    build:
#      context: client
#      dockerfile: Dockerfile
#    volumes:
#      - ./server/medias/:/app/medias
#    ports:
#      - "80:80"