version: "3.9"

services:
  database:
    image: postgres:17.1
    volumes:
      - ./server/database/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:80"