FROM python:3.12

WORKDIR /dirforprod

COPY requirements_for_prod.txt .

RUN pip install --no-cache-dir -r requirements_for_prod.txt

COPY app server/app/
COPY database/confdb.py server/database/
COPY database/models.py server/database/
COPY database/getter_variables.py server/database/

ENV PYTHONPATH=/dirforprod/

CMD ["uvicorn", "server.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
