FROM python:3.12

WORKDIR /dirfortest

COPY requirements_for_tests.txt .

RUN pip install --no-cache-dir -r requirements_for_tests.txt

COPY app server/app/
COPY tests server/tests/
COPY database/confdb.py server/database/
COPY database/models.py server/database/
COPY database/getter_variables.py server/database/

ENV PYTHONPATH=/dirfortest/

CMD ["pytest"]
