FROM python:3.12

WORKDIR /dirfortest

COPY requirements_for_prod.txt .

RUN pip install --no-cache-dir -r requirements_for_prod.txt

COPY app server/app/
COPY tests server/tests/
COPY database/confdb.py server/database/confdb.py
COPY database/models.py server/database/models.py
COPY database/getter_variables.py server/database/getter_variables.py

ENV PYTHONPATH=/dirfortest/

CMD ["pytest"]
